version: "3.8"

volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:

networks:
  n8n:

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ["n8n"]
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    networks: ["n8n"]
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - OLLAMA_HOST=ollama:11434
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    env_file:
      - .env
    hostname: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.dev-oi.fr`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certResolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    hostname: openwebui
    networks: ["n8n"]
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama-cpu
    volumes:
      - open-webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.dev-oi.fr`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls.certResolver=letsencrypt"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    networks: ["n8n"]
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama-cpu:
    image: ollama/ollama:latest
    networks: ["n8n"]
    ports:
      - 11434:11434
    volumes:
      - ollama_storage:/root/.ollama
